export enum ActionTypes {
  ADD_TODO = 'ADD_TODO',
  ADD_SUBTASK = 'ADD_SUBTASK',
  DELETE_TODO = 'DELETE_TODO',
  EDIT_TODO = 'EDIT_TODO',
  UPDATE_TODO = 'UPDATE_TODO',
  LOAD_REQUEST = 'LOAD_REQUEST',
  TOGGLE_TODO = 'TOGGLE_TODO',
  TOGGLE_EDIT_TODO = 'TOGGLE_EDIT_TODO',
}
